# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/TA/Dropbox/script_server/core/maya/rftool/prop_it/ui.ui'
#
# Created: Sat Jan 07 19:34:16 2017
#      by: pyside-uic 0.2.14 running on PySide 1.2.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_PropItUI(object):
    def setupUi(self, PropItUI):
        PropItUI.setObjectName("PropItUI")
        PropItUI.resize(286, 450)
        self.centralwidget = QtGui.QWidget(PropItUI)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.project_label_2 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.project_label_2.setFont(font)
        self.project_label_2.setObjectName("project_label_2")
        self.gridLayout_3.addWidget(self.project_label_2, 0, 0, 1, 1)
        self.project_label = QtGui.QLabel(self.centralwidget)
        self.project_label.setObjectName("project_label")
        self.gridLayout_3.addWidget(self.project_label, 0, 1, 1, 1)
        self.project_label_3 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.project_label_3.setFont(font)
        self.project_label_3.setObjectName("project_label_3")
        self.gridLayout_3.addWidget(self.project_label_3, 1, 0, 1, 1)
        self.type_label = QtGui.QLabel(self.centralwidget)
        self.type_label.setObjectName("type_label")
        self.gridLayout_3.addWidget(self.type_label, 1, 1, 1, 1)
        self.project_label_4 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.project_label_4.setFont(font)
        self.project_label_4.setObjectName("project_label_4")
        self.gridLayout_3.addWidget(self.project_label_4, 2, 0, 1, 1)
        self.project_label_5 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.project_label_5.setFont(font)
        self.project_label_5.setObjectName("project_label_5")
        self.gridLayout_3.addWidget(self.project_label_5, 3, 0, 1, 1)
        self.subtype_label = QtGui.QLabel(self.centralwidget)
        self.subtype_label.setObjectName("subtype_label")
        self.gridLayout_3.addWidget(self.subtype_label, 2, 1, 1, 1)
        self.asset_label = QtGui.QLabel(self.centralwidget)
        self.asset_label.setObjectName("asset_label")
        self.gridLayout_3.addWidget(self.asset_label, 3, 1, 1, 1)
        self.project_label_6 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.project_label_6.setFont(font)
        self.project_label_6.setObjectName("project_label_6")
        self.gridLayout_3.addWidget(self.project_label_6, 4, 0, 1, 1)
        self.id_label = QtGui.QLabel(self.centralwidget)
        self.id_label.setObjectName("id_label")
        self.gridLayout_3.addWidget(self.id_label, 4, 1, 1, 1)
        self.gridLayout_3.setColumnStretch(0, 1)
        self.gridLayout_3.setColumnStretch(1, 3)
        self.verticalLayout_2.addLayout(self.gridLayout_3)
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.deleteProxy_checkBox = QtGui.QCheckBox(self.centralwidget)
        self.deleteProxy_checkBox.setChecked(True)
        self.deleteProxy_checkBox.setObjectName("deleteProxy_checkBox")
        self.gridLayout.addWidget(self.deleteProxy_checkBox, 6, 0, 1, 1)
        self.ref_checkBox = QtGui.QCheckBox(self.centralwidget)
        self.ref_checkBox.setChecked(True)
        self.ref_checkBox.setObjectName("ref_checkBox")
        self.gridLayout.addWidget(self.ref_checkBox, 7, 0, 1, 1)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 3, 0, 1, 1)
        self.export_pushButton = QtGui.QPushButton(self.centralwidget)
        self.export_pushButton.setMinimumSize(QtCore.QSize(0, 40))
        self.export_pushButton.setObjectName("export_pushButton")
        self.gridLayout.addWidget(self.export_pushButton, 5, 0, 1, 1)
        self.center_pushButton = QtGui.QPushButton(self.centralwidget)
        self.center_pushButton.setMinimumSize(QtCore.QSize(0, 30))
        self.center_pushButton.setObjectName("center_pushButton")
        self.gridLayout.addWidget(self.center_pushButton, 0, 0, 1, 1)
        self.createRig_pushButton = QtGui.QPushButton(self.centralwidget)
        self.createRig_pushButton.setMinimumSize(QtCore.QSize(0, 30))
        self.createRig_pushButton.setObjectName("createRig_pushButton")
        self.gridLayout.addWidget(self.createRig_pushButton, 1, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.res_comboBox = QtGui.QComboBox(self.centralwidget)
        self.res_comboBox.setObjectName("res_comboBox")
        self.horizontalLayout_4.addWidget(self.res_comboBox)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 2)
        self.gridLayout.addLayout(self.horizontalLayout_4, 4, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.line_3 = QtGui.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_2.addWidget(self.line_3)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.propCam_pushButton = QtGui.QPushButton(self.centralwidget)
        self.propCam_pushButton.setMinimumSize(QtCore.QSize(0, 30))
        self.propCam_pushButton.setObjectName("propCam_pushButton")
        self.horizontalLayout_6.addWidget(self.propCam_pushButton)
        self.currentCam_pushButton = QtGui.QPushButton(self.centralwidget)
        self.currentCam_pushButton.setMinimumSize(QtCore.QSize(0, 30))
        self.currentCam_pushButton.setObjectName("currentCam_pushButton")
        self.horizontalLayout_6.addWidget(self.currentCam_pushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.line_4 = QtGui.QFrame(self.centralwidget)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_2.addWidget(self.line_4)
        self.duplicateReference_pushButton = QtGui.QPushButton(self.centralwidget)
        self.duplicateReference_pushButton.setMinimumSize(QtCore.QSize(0, 40))
        self.duplicateReference_pushButton.setObjectName("duplicateReference_pushButton")
        self.verticalLayout_2.addWidget(self.duplicateReference_pushButton)
        PropItUI.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(PropItUI)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 286, 21))
        self.menubar.setObjectName("menubar")
        PropItUI.setMenuBar(self.menubar)

        self.retranslateUi(PropItUI)
        QtCore.QMetaObject.connectSlotsByName(PropItUI)

    def retranslateUi(self, PropItUI):
        PropItUI.setWindowTitle(QtGui.QApplication.translate("PropItUI", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.project_label_2.setText(QtGui.QApplication.translate("PropItUI", "Project : ", None, QtGui.QApplication.UnicodeUTF8))
        self.project_label.setText(QtGui.QApplication.translate("PropItUI", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.project_label_3.setText(QtGui.QApplication.translate("PropItUI", "Type : ", None, QtGui.QApplication.UnicodeUTF8))
        self.type_label.setText(QtGui.QApplication.translate("PropItUI", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.project_label_4.setText(QtGui.QApplication.translate("PropItUI", "SubType : ", None, QtGui.QApplication.UnicodeUTF8))
        self.project_label_5.setText(QtGui.QApplication.translate("PropItUI", "SubType : ", None, QtGui.QApplication.UnicodeUTF8))
        self.subtype_label.setText(QtGui.QApplication.translate("PropItUI", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.asset_label.setText(QtGui.QApplication.translate("PropItUI", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.project_label_6.setText(QtGui.QApplication.translate("PropItUI", "ID : ", None, QtGui.QApplication.UnicodeUTF8))
        self.id_label.setText(QtGui.QApplication.translate("PropItUI", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteProxy_checkBox.setText(QtGui.QApplication.translate("PropItUI", "Delete Proxy", None, QtGui.QApplication.UnicodeUTF8))
        self.ref_checkBox.setText(QtGui.QApplication.translate("PropItUI", "Replace Proxy with Reference", None, QtGui.QApplication.UnicodeUTF8))
        self.export_pushButton.setText(QtGui.QApplication.translate("PropItUI", "Export", None, QtGui.QApplication.UnicodeUTF8))
        self.center_pushButton.setText(QtGui.QApplication.translate("PropItUI", "Center Asset", None, QtGui.QApplication.UnicodeUTF8))
        self.createRig_pushButton.setText(QtGui.QApplication.translate("PropItUI", "Create Rig", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("PropItUI", "Res", None, QtGui.QApplication.UnicodeUTF8))
        self.propCam_pushButton.setText(QtGui.QApplication.translate("PropItUI", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.currentCam_pushButton.setText(QtGui.QApplication.translate("PropItUI", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.duplicateReference_pushButton.setText(QtGui.QApplication.translate("PropItUI", "Duplicate Reference", None, QtGui.QApplication.UnicodeUTF8))

